# Generated by Django 3.2.9 on 2021-11-17 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInitialCode',
            fields=[
                ('emInit_id', models.AutoField(primary_key=True, serialize=False)),
                ('initialCode', models.CharField(max_length=2)),
                ('employee_id', models.IntegerField()),
                ('activeStatus', models.BooleanField(default=False)),
                ('isLock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('investigator', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectReport',
            fields=[
                ('subReport_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('trainYear', models.IntegerField()),
                ('score', models.IntegerField()),
                ('score_pass', models.IntegerField()),
                ('instructor', models.CharField(max_length=255)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.IntegerField()),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('activeStatus', models.BooleanField(default=True)),
                ('responsibility', models.ManyToManyField(to='BACC_Backend.Responsibility')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('initialCode', models.CharField(max_length=2)),
                ('title', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('ว่าที่ ร.ต.', 'ว่าที่ ร.ต.'), ('ร.ต.', 'ร.ต.')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=255)),
                ('surname_eng', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('ผู้อำนวยการฝ่ายบริหารศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ', 'ผู้อำนวยการฝ่ายบริหารศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ'), ('ผู้อำนวยการศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ', 'ผู้อำนวยการศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ'), ('ผู้อำนวยการสนับสนุนศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ', 'ผู้อำนวยการสนับสนุนศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ'), ('ผู้จัดการงานควบคุมจราจรทางอากาศ (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)', 'ผู้จัดการงานควบคุมจราจรทางอากาศ (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)'), ('ผู้จัดการงานบริหารทั่วไป', 'ผู้จัดการงานบริหารทั่วไป'), ('เจ้าหน้าที่ควบคุมจราจรทางอากาศ 2 (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)', 'เจ้าหน้าที่ควบคุมจราจรทางอากาศ 2 (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)'), ('ผู้ช่วยเจ้าหน้าที่ควบคุมจราจรทางอากาศ', 'ผู้ช่วยเจ้าหน้าที่ควบคุมจราจรทางอากาศ'), ('เจ้าหน้าที่ควบคุมจราจรทางอากาศ 1 (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)', 'เจ้าหน้าที่ควบคุมจราจรทางอากาศ 1 (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)'), ('ผู้ช่วยเจ้าหน้าที่ควบคุมจราจรทางอากาศ', 'ผู้ช่วยเจ้าหน้าที่ควบคุมจราจรทางอากาศ'), ('เจ้าหน้าที่บริหารงานทั่วไปอาวุโส', 'เจ้าหน้าที่บริหารงานทั่วไปอาวุโส'), ('เจ้าหน้าที่ฝึกหัดควบคุมจราจรทางอากาศ (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)', 'เจ้าหน้าที่ฝึกหัดควบคุมจราจรทางอากาศ (ศูนย์ควบคุมจราจรทางอากาศเส้นทางบินกรุงเทพ)'), ('เจ้าหน้าที่บริหารทั่วไป', 'เจ้าหน้าที่บริหารทั่วไป'), ('นักเรียนฝึกหัดควบคุมจราจรทางอากาศ', 'นักเรียนฝึกหัดควบคุมจราจรทางอากาศ')], max_length=255)),
                ('division', models.CharField(choices=[('สจ.ศจ.', 'สจ.ศจ.'), ('คจ.ศจ.', 'ศจ.ศจ.')], max_length=255)),
                ('area', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Day-work', 'Day-work')], max_length=50)),
                ('shift', models.CharField(max_length=10)),
                ('activeStatus', models.BooleanField(default=True)),
                ('responsibility', models.ManyToManyField(to='BACC_Backend.Responsibility')),
            ],
        ),
    ]
